# Generated by Django 5.0.1 on 2024-09-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
