# Generated by Django 5.0.1 on 2024-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_kupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='kupon',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
