# Generated by Django 5.0.1 on 2024-09-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_kupon_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
