# Generated by Django 5.0.1 on 2024-09-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_kupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kupon', to='main.kupon'),
        ),
    ]
