# Generated by Django 5.0.1 on 2024-09-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_transaction_kupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('payoff_date', models.DateTimeField()),
                ('bank_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bank_balance')),
            ],
        ),
    ]
