# Generated by Django 5.0.1 on 2024-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='credit_taken_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
