# Generated by Django 5.0.1 on 2024-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_credit_credit_taken_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='how_many_months',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
