# Generated by Django 5.0.1 on 2024-09-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_credit_how_many_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payoff_date',
            field=models.JSONField(default=dict),
        ),
    ]
