# Generated by Django 5.0.1 on 2024-09-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_credit_money_back_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='procent_stavka',
            field=models.CharField(default='0%', max_length=5),
        ),
    ]
