# Generated by Django 5.0.1 on 2024-09-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_credit_procent_stavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='delinquency',
            field=models.BooleanField(default=False),
        ),
    ]
