# Generated by Django 5.0.1 on 2024-09-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_credit_delinquency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='delinquency',
        ),
    ]
