# Generated by Django 5.0.1 on 2024-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_credit_delinquency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='procent_stavka',
            field=models.IntegerField(),
        ),
    ]
