# Generated by Django 5.0.1 on 2024-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_credit_procent_stavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit_taken_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
