# Generated by Django 5.0.1 on 2024-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_credit_credit_taken_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='current_procent_stavka',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
