# Generated by Django 5.0.1 on 2024-09-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_credit_current_procent_stavka'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
