# Generated by Django 5.0.1 on 2024-09-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_myuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
