# Generated by Django 5.0.1 on 2024-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_user_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
